name: Deploy GitHub Pages
on:
  push: 
    branch: main

jobs:
  deploy:
    permissions:
      pages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4 

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - uses: actions/configure-pages@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v2
        
